pub const SYS_GETCWD: usize = 17; //获取当前工作目录
pub const SYS_PIPE2: usize = 59; //创建管道
pub const SYS_DUP: usize = 23; //复制文件描述符
pub const SYS_CHDIR: usize = 49; //切换工作目录
pub const SYS_DUP3: usize = 24; //复制文件描述符，并指定新的文件描述符
pub const SYS_chdir: usize = 49; //切换工作目录
pub const SYS_OPENAT: usize = 56; //打开或创建一个文件
pub const SYS_CLOSE: usize = 57; //关闭一个文件描述符
pub const SYS_GETDENTS64: usize = 61; //获取目录条目
pub const SYS_READ: usize = 63; //从一个文件描述符中读取
pub const SYS_WRITE: usize = 64; //从一个文件描述符写入
pub const SYS_LINKAT: usize = 37; //创建文件的链接
pub const SYS_UNLINKAT: usize = 35; //移除制定文件的链接（可用于删除文件）
pub const SYS_MKDIRAT: usize = 34; //创建目录
pub const SYS_UMOUNT2: usize = 39; //卸载文件系统
pub const SYS_MOUNT: usize = 40; //挂载文件系统
pub const SYS_FSTAT: usize = 80; //获取文件状态
pub const SYS_CLONE: usize = 220; //创建一个子进程
pub const SYS_EXECVE: usize = 221; //执行一个指定的程序
pub const SYS_WAIT4: usize = 260; //等待进程改变状态
pub const SYS_EXIT: usize = 93;  //触发进程终止，无返回值
pub const SYS_GETPPID : usize = 173; //获取父进程ID
pub const SYS_GETPID : usize = 172; //获取进程ID
pub const SYS_BRK: usize = 214; //修改数据段的大小
pub const SYS_MUNMAP: usize = 215; //将文件或设备取消映射到内存中
pub const SYS_MMAP: usize = 222; //将文件或设备映射到内存中
pub const SYS_TIMES: usize = 153; //获取进程时间
pub const SYS_UNAME: usize = 160; //打印系统信息
pub const SYS_SCHED_YIELD: usize = 124; //让出调度器
pub const SYS_GET_TIMEOFDAY:usize = 169; //获取时间
pub const SYS_NANOSLEEP: usize = 101; //执行线程睡眠，sleep()库函数都基于此系统调用 
